CREATE DATABASE TiendaInformatica;

USE TiendaInformatica;

CREATE TABLE FABRICANTES (
    Codigo INT AUTO_INCREMENT PRIMARY KEY,
    Nombre NVARCHAR(100)
);

CREATE TABLE ARTICULOS (
    Codigo INT AUTO_INCREMENT PRIMARY KEY,
    Nombre NVARCHAR(100),
    Precio INT,
    Fabricante INT,
    FOREIGN KEY (Fabricante) REFERENCES FABRICANTES(Codigo)
);